### ISSUE TITLE
departmentScreen(Civil)

### ISSUE THREAD

**Issue by arjundubey-cr** [arjundubey-cr/cwebsite-react#44]
_**Create screens for every branch **_

CE (REF: [cepage_lkuniv](https://udrc.lkouniv.ac.in/Department/DepartmentDetail/History?dept=59)
> Numbers tabs can be increased or decreased depending upon how the structure is laid out.
- [x] About
- [x] Vision&Mission
- [x] Courses Offered&Thrust Areas
- [x] Faculty 
- [x] Resources
- [x] Achievements

**Comment by Shubhendra-Bahadur** [comment]
assign me

**Comment by arjundubey-cr** [comment]
completed by @Shubhendra-Bahadur  in #59
