### ISSUE TITLE
departmentScreens(CSE)

### ISSUE THREAD

**Issue by arjundubey-cr** [arjundubey-cr/cwebsite-react#7]
_**Create screens for every branch **_

CSE
> Numbers tabs can be increased or decreased depending upon how the structure is laid out.
- [ ] About
- [ ] Vision&Mission
- [ ] Courses Offered&Thrust Areas
- [ ] Faculty 
- [ ] Resources
- [ ] Achievements

**Comment by Shubhendra-Bahadur** [comment]
i will proceed with this issue, assign this to me.

**Comment by arjundubey-cr** [comment]
done #31
