### ISSUE TITLE
department screen (ECE)

### ISSUE THREAD

**Issue by arjundubey-cr** [arjundubey-cr/cwebsite-react#9]
_**Create screens for every branch **_

ECE (REF: [ecepage_lkuniv](https://udrc.lkouniv.ac.in/Department/DepartmentDetail/History?dept=57)
> Numbers tabs can be increased or decreased depending upon how the structure is laid out.
- [ ] About
- [ ] Vision&Mission
- [ ] Courses Offered&Thrust Areas
- [ ] Faculty 
- [ ] Resources
- [ ] Achievements

**Comment by Shubhendra-Bahadur** [comment]
assign me

**Comment by arjundubey-cr** [comment]
sure

**Comment by arjundubey-cr** [comment]
completed by @Shubhendra-Bahadur in-branch side-project merged into main
